server:
  port: 8081

spring:
  application:
    name: canteen-user-service
  
  # Nacos服务发现配置
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
        namespace: public
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/canteen_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # Security配置
  # security:
  #   user:
  #     name: admin
  #     password: admin

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    enable-sql-runner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  check-config-location: false
  # 完全禁用DDL功能
  ddl-auto: none
  
# 禁用自动DDL
management:
  endpoints:
    enabled-by-default: false

# 日志配置
logging:
  level:
    com.canteen.user: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 系统配置
canteen:
  order-service:
    url: http://localhost:8083