server:
  port: 8084

spring:
  application:
    name: canteen-recommend-service

# 日志配置
logging:
  level:
    com.canteen.recommend: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"