server:
  port: 8080

spring:
  application:
    name: canteen-gateway

# 日志配置
logging:
  level:
    com.canteen.gateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"