server:
  port: 8082

spring:
  application:
    name: canteen-product-service
  
  # 禁用Nacos服务发现
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  
  # 允许bean定义覆盖
  main:
    allow-bean-definition-overriding: true
  
  # 数据库配置 - 使用H2内存数据库避免MySQL依赖
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  
  # H2数据库控制台
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 禁用数据库初始化
  sql:
    init:
      mode: never
  
  # 禁用JPA相关配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

# 日志配置
logging:
  level:
    com.canteen.product: DEBUG
    org.springframework.cloud: OFF
    com.alibaba.nacos: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"