server:
  port: 8084

spring:
  application:
    name: canteen-recommend-service
  
  # Nacos服务发现配置
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
        namespace: public

# 日志配置
logging:
  level:
    com.canteen.recommend: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"